config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :vinos
  resources :cepas

  root 'users#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cepa.rb
class Cepa < ApplicationRecord
    has_many :ensamblajes
    has_many :vinos, through: :ensamblajes
end

app/models/ensamblaje.rb
class Ensamblaje < ApplicationRecord
  belongs_to :vino
  belongs_to :cepa
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #before_action :authenticate_user!
end

app/models/vino.rb
class Vino < ApplicationRecord
    has_many :ensamblajes
    has_many :cepas, through: :ensamblajes
    accepts_nested_attributes_for :ensamblajes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cepas_controller.rb
class CepasController < ApplicationController
  before_action :set_cepa, only: %i[ show edit update destroy ]

  # GET /cepas or /cepas.json
  def index
    @cepas = Cepa.all
  end

  # GET /cepas/1 or /cepas/1.json
  def show
  end

  # GET /cepas/new
  def new
    @cepa = Cepa.new
  end

  # GET /cepas/1/edit
  def edit
  end

  # POST /cepas or /cepas.json
  def create
    @cepa = Cepa.new(cepa_params)

    respond_to do |format|
      if @cepa.save
        format.html { redirect_to cepa_url(@cepa), notice: "Cepa was successfully created." }
        format.json { render :show, status: :created, location: @cepa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cepa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cepas/1 or /cepas/1.json
  def update
    respond_to do |format|
      if @cepa.update(cepa_params)
        format.html { redirect_to cepa_url(@cepa), notice: "Cepa was successfully updated." }
        format.json { render :show, status: :ok, location: @cepa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cepa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cepas/1 or /cepas/1.json
  def destroy
    @cepa.destroy

    respond_to do |format|
      format.html { redirect_to cepas_url, notice: "Cepa was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cepa
      @cepa = Cepa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cepa_params
      params.require(:cepa).permit(:nombre)
    end
end

app/controllers/vinos_controller.rb
class VinosController < ApplicationController
  before_action :set_vino, only: %i[ show edit update destroy ]

  # GET /vinos or /vinos.json
  def index
    @vinos = Vino.all
  end

  # GET /vinos/1 or /vinos/1.json
  def show
  end

  # GET /vinos/new
  def new
    @vino = Vino.new
    @cepas = Cepa.all
    @vino.ensamblajes.build
  end

  # GET /vinos/1/edit
  def edit
    @pos = 0
    if @vino.ensamblajes.count == 0
      @cepas = Cepa.all
      @vino.ensamblajes.build
    end
  end

  # POST /vinos or /vinos.json
  def create
    @vino = Vino.new(vino_params)

    respond_to do |format|
      if @vino.save
        format.html { redirect_to vino_url(@vino), notice: "Vino was successfully created." }
        format.json { render :show, status: :created, location: @vino }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vino.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vinos/1 or /vinos/1.json
  def update
    respond_to do |format|
      if @vino.update(vino_params)
        format.html { redirect_to vino_url(@vino), notice: "Vino was successfully updated." }
        format.json { render :show, status: :ok, location: @vino }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vino.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vinos/1 or /vinos/1.json
  def destroy
    @vino.destroy

    respond_to do |format|
      format.html { redirect_to vinos_url, notice: "Vino was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vino
      @vino = Vino.includes(:cepas).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vino_params
      params.require(:vino).permit(:nombre, ensamblajes_attributes: [:id, :cepa_id, :porcentaje])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cepas_helper.rb
module CepasHelper
end

app/helpers/vinos_helper.rb
module VinosHelper
end

app/views/cepas/_cepa.html.erb
<div id="<%= dom_id cepa %>">
  <p>
    <strong>Nombre:</strong>
    <%= cepa.nombre %>
  </p>

</div>

app/views/cepas/_form.html.erb
<%= form_with(model: cepa) do |form| %>
  <% if cepa.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cepa.errors.count, "error") %> prohibited this cepa from being saved:</h2>

      <ul>
        <% cepa.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cepas/edit.html.erb
<h1>Editing cepa</h1>

<%= render "form", cepa: @cepa %>

<br>

<div>
  <%= link_to "Show this cepa", @cepa %> |
  <%= link_to "Back to cepas", cepas_path %>
</div>

app/views/cepas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cepas</h1>

<div id="cepas">
  <% @cepas.each do |cepa| %>
    <%= render cepa %>
    <p>
      <%= link_to "Show this cepa", cepa %>
    </p>
  <% end %>
</div>

<%= link_to "New cepa", new_cepa_path %>

app/views/cepas/new.html.erb
<h1>New cepa</h1>

<%= render "form", cepa: @cepa %>

<br>

<div>
  <%= link_to "Back to cepas", cepas_path %>
</div>

app/views/cepas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cepa %>

<div>
  <%= link_to "Edit this cepa", edit_cepa_path(@cepa) %> |
  <%= link_to "Back to cepas", cepas_path %>

  <%= button_to "Destroy this cepa", @cepa, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cepas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vinos/_form.html.erb
<%= form_with(model: vino) do |form| %>
  <% if vino.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vino.errors.count, "error") %> prohibited this vino from being saved:</h2>

      <ul>
        <% vino.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <% if vino.ensamblajes.count != 0 %>
    <div>
      <%= form.fields_for :ensamblajes do |f_ensamblajes| %>
        <%= f_ensamblajes.label vino.ensamblajes[@pos].cepa.nombre %>
        <%= f_ensamblajes.label :porcentaje %>
        <%= f_ensamblajes.number_field :porcentaje %>
        <% @pos += 1 %>
      <% end %>
    </div>
  <% else %>
    <% @cepas.each do |cepa| %>
      <div>
        <%= form.fields_for :ensamblajes do |f_ensamblajes| %>
          <%= f_ensamblajes.label :cepa_id, cepa.nombre %>
          <%= f_ensamblajes.hidden_field :cepa_id, value: cepa.id %>

          <%= f_ensamblajes.label :porcentaje %>
          <%= f_ensamblajes.number_field :porcentaje, value: 0 %>
        <% end %>
      </div>
    <% end %>
  <% end %>

    <div>
    <h1>Rama desafío evaluado</h1>
    </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vinos/_vino.html.erb
<div id="<%= dom_id vino %>">
  <p>
    <strong>Nombre:</strong>
    <%= vino.nombre %>
  </p>

</div>

app/views/vinos/edit.html.erb
<h1>Editing vino</h1>

<%= render "form", vino: @vino %>

<br>

<div>
  <%= link_to "Show this vino", @vino %> |
  <%= link_to "Back to vinos", vinos_path %>
</div>

app/views/vinos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Vinos</h1>

<div id="vinos">
  <% @vinos.each do |vino| %>
    <%= render vino %>
    <p>
      <%= link_to "Show this vino", vino %>
    </p>
  <% end %>
</div>

<%= link_to "New vino", new_vino_path %>

app/views/vinos/new.html.erb
<h1>New vino</h1>

<%= render "form", vino: @vino %>

<br>

<div>
  <%= link_to "Back to vinos", vinos_path %>
</div>

app/views/vinos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vino %>

<div>
  <%= link_to "Edit this vino", edit_vino_path(@vino) %> |
  <%= link_to "Back to vinos", vinos_path %>

  <%= button_to "Destroy this vino", @vino, method: :delete %>
</div>